on: push

jobs:
  use-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and run docker file
        run: |
          docker build -t helloworld:latest .
          docker run helloworld