trigger: [push]

runs-on: ubuntu-latest

jobs:
  use-docker:
    steps:
      - step: Checkout
        uses: actions/checkout@v4
      - step: Build-docker
        runs: docker build -t helloworld:latest .
      - step: Run-docker
        runs: docker run helloworld