on: push

jobs:
  use-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build-docker
        run: docker build -t helloworld:latest .
      - name: Run-docker
        run: docker run helloworld